### ISSUE TITLE
Add a feed?

### ISSUE THREAD

**Issue by tfausak** [VynM/Comutations#1]
Hi! I am the editor of Haskell Weekly. I would like to be notified when you publish a new post, but as far as I can tell your site does not have a feed. Would you mind adding an Atom or RSS feed? Hakyll supports this out of the box: https://jaspervdj.be/hakyll/tutorials/05-snapshots-feeds.html. Thanks!

**Comment by VynM** [comment]
[Done!](https://vynm.github.io/Comutations/atom.xml)

Thank you so much for your interest. I've never used Atom or RSS before, so I was putting off adding a feed until it became necessary. You've given me a great reason to add one. Took a little bit of figuring out, but it wasn't too hard after all. I hope it works as expected. All I know is that the [feed page](https://vynm.github.io/Comutations/atom.xml) shows the posts. Thanks again!
(And the next post is in the works, so it won't be long now)

**Comment by tfausak** [comment]
Great, thanks!
